name: Sync Course Content on PR

on:
  push:
    branches: [sync-course]
  pull_request:
    branches: [sync-course]

jobs:
  sync-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository with PR branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}  # Checkout the PR branch specifically
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run download script
      run: python list_course_assignments.py

    - name: Commit and push changes
      id: commit
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        # Only commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Automated update: Downloaded latest content"
          git push
        fi